apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: web
    image: toshikx/otus:nginx-server
    ports:
      - containerPort: 8000
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: init-web-server
    image: busybox:1.31.0
    command:  ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}